[package]
name = "pyrite_render"
description = "Pyrite's higher level rendering library."
version = "0.1.0"
edition = "2021"

[dependencies]
pyrite_app = { path = "../pyrite_app" }
pyrite_desktop = { path = "../pyrite_desktop" }
pyrite_vulkan = { path = "../pyrite_vulkan" }
pyrite_util = { path = "../pyrite_util" }
ash = "0.37.3+1.3.251"
uuid = { version = "1.5.0", features = ["v4", "fast-rng"] }
